### ISSUE TITLE
Fix netlify contact form

### ISSUE THREAD

**Issue by KilianZimmerer** [BerlinzuDir/decilo-frontend#27]
Netlify Forms does not receive the contact form input after submission.

**Comment by jakobkolb** [comment]
Seems to be an issue with nextjs and its handling of netlify forms - see [here](https://answers.netlify.com/t/forms-not-being-sent-with-next-js/)

**Comment by KilianZimmerer** [comment]
Did you already look through this? As a first try I would adapt all attributes as shown there:

https://simplernerd.com/nextjs-netlify-form/

**Comment by jakobkolb** [comment]
I've remembered that I ran into this before. I think I can handle it.
